name: flit
description: Flutter Desktop Toolkit
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true